config/routes.rb
Rails.application.routes.draw do
  resources :games
  resources :purchases
  resources :reviews
  resources :game_studios
  resources :users
  
  # root to: 'auth#login'
  get 'create', to: "users#new"
  get '/login', to: "auth#login", as: "login" 
  post '/login', to: "auth#verify_username"
  get '/logout', to: "auth#logout", as: "logout"
  post '/users/new', to: "auth#verify_username"
  post '/purchases', to: "purchases#create"
  post 'purchases/:id', to: "purchases#update", as:"update_purchases"
  post 'reviews/:id', to: "reviews#create", as: "update_review"
  post'reviews/new', to: 'reviews#create', as: "create_review"
  

end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
    belongs_to :game_studio
    has_many :purchases
    has_many :reviews, through: :purchases
    has_many :users, through: :purchases
end

app/models/game_studio.rb
class GameStudio < ApplicationRecord
    has_many :games
end

app/models/purchase.rb
class Purchase < ApplicationRecord
    belongs_to :game
    belongs_to :user
    has_many :reviews
    validates :game_id, uniqueness: true
    validates :user_id, uniqueness: true
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :purchase
end

app/models/user.rb
class User < ApplicationRecord
    has_many :purchases
    has_many :games, through: :purchases
    validates :name, confirmation: true
    validates :password, confirmation: true
    has_secure_password
   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
  helper_method :current_user, :redirect_user, :logged_in?

  def logged_in?
    !!current_user
  end

  def current_user
    user = User.find(session[:user_id]) if session[:user_id]
  end

  def redirect_user
    if !current_user
      flash[:message] = "Please login to view this data"
      redirect_to purchases_path
    end
  end
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController
    def login
      # reset_session 
    end
  
    def verify_username 
      @user = User.find_by(name: params[:auth][:username])
      if @user && @user.authenticate(params[:auth][:password])
        session[:user_id] = @user.id
        redirect_to purchases_path
      else
        flash[:message] = "Please try again"
        render :login
      end
    end

#     def create
#       user = User.create(user_path)
#       redirect_to user_path
# end
    def logout
      session.clear
      redirect_to login_path
    end
  end 

app/controllers/game_studios_controller.rb
class GameStudiosController < ApplicationController
    def show
        @game_studio = GameStudio.find(params[:id])
    end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
    def show
        @game = Game.find(params[:id])
    end

    def
private

def game_params
    params.require(:game).permit(:title, :release_date, :game_studios_id)
end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController

    def index
        @purchases = Purchase.all
        @reviews = Review.all
    end

    def show
        @purchase = Purchase.find(params[:id])
        session[:purchase_id] = @purchase.id
    end

    def create
        @purchase = Purchase.new(params[:review])
            if @review.save
                redirect_to reviews_path
        else
            render "new"
            end
        end

    def edit
        @purchase = Purchase.find(params[:id])
    end
    
    def update
        @purchase = Purchase.find(params[:id])
       redirect_to reviews_path
     end

     private 

     def purchase_params
        params.require(:purchase).permit( :game_id, :user_id, :purchase_id)
     end
  end

   

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
   

    def index
        @reviews = Review.all
        @purchases = Purchase.all
    end

    def show
    @review = Review.find(params[:id])
    end

    def new
        @review = Review.new
        @purchase_id = session[:purchase_id]
    end


    def create
        @review = Review.new(review_params)
       if  @review.save
         redirect_to purchase_path(@review.purchase_id)
        else
            flash[:alert] = "Review Did Not Post"
            render :new
        end
    end

    def edit
        @review = Review.find(params[:id])
    end

    def update
        @review = Review.find(params[:id])
        if @review.update(review_params)
            redirect_to purchase_path(@review.purchase_id)
        else
            flash[:error] 
            render :edit
        end
    end


def destroy
   @review = Review.destroy(params[:id])
    redirect_to purchase_path(@review.purchase_id)
end

private 

def review_params
    params.require(:review).permit(:reviewed_game, :rating, :purchase_id)
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def index
        @users = User.all
    end

    def new
        @user = User.new
    end

      def create
        user = User.create(user_params)
        redirect_to purchases_path
    end

    def edit
        @user = User.find(params[:id])
    end

    def update
        user = User.find(params[:id])
        user = User.create(name: params[:name], password: params[:password])
    end

    def show
        @user = User.find(params[:id])
    end
    

    private
    def user_params
        params.require(:user).permit(:username, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_studios_helper.rb
module GameStudiosHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
   <%= csrf_meta_tags %>
    <title>User</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%# <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %> 
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/1.11.8/semantic.min.css"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.co m/ajax/libs/semantic-ui/1.11.8/semantic.min.js"></script>
  </head>
  <div class="navbar">
  <div class=>
    <a href="/" class="item">
      <h1></h1>
    </a>
      <div class="right menu">
        <% if logged_in? %>
          <%# <%= link_to 'Create a New User', new_user_path, {class: 'item'} %> 
               <%= link_to 'Dashboard', purchases_path, {class: 'item'} %><br>
          <%= link_to 'Logout', logout_path, {class: 'item'} %>
        <%# <% else %>
          <%# <%= link_to 'Login', login_path, {class: 'item'} %> 
          <%# <%= link_to 'Create a New User', new_user_path, {class: 'item'} %> 
        <% end %>
      </div>
    </div>
</div>
  <body>
    <div class="ui centered grid ">
      <div class="eight wide column">

        <%= yield %>

      </div>
    </div>
  </body>
</html> 

app/views/purchases/index.html.erb
<h1>Gaming Dashboard </h1>

<% @purchases.each do |purchase| %>
<%# <%= purchase.game %><br>   
    <%= link_to purchase.game.title, purchase %><br>   


<% end %>
<%= link_to 'Previous Page', url_for(:back) %>

app/views/purchases/show.html.erb
Game Title: <h1><%= @purchase.game.title %></h1>
Release Date: <h1><%= @purchase.game.release_date %></h1>  
Game Studio: <h1><%= @purchase.game.game_studio.name %></h1>
Address: <h1><%= @purchase.game.game_studio.location %></h1>  
<h1> Current Reviews You've Given! </h1>
<h2><% @purchase.reviews.each do |review| %></h2>
<%= link_to review.reviewed_game, review_path(review) %><br>
<% end %>
<h1> WRITE A NEW REVIEW! </h1>
<%= link_to "Write Your Review Here!", new_review_path(purchase_id: @purchase.id)  %><br>



<%= link_to 'Previous Page', url_for(:back) %>

app/views/reviews/edit.html.erb
<h1>Update Review! </h1>

 <%= flash[:alert] %>


<%= form_for @review do |f| %>
    <%= f.text_area(:reviewed_game, :size => "100x20") %>
   Leave Your Rating Here: <%= f.number_field(:rating, within: 0..5) %>
    <%= f.hidden_field :purchase_id, value: @review.purchase_id %>
    <%= f.submit "Submit Review" %>
<% end %>

<%= link_to 'Previous Page', url_for(:back) %>

app/views/reviews/index.html.erb
<h1> Reviews </h1>
<% @reviews.each do |review| %>
<%= link_to review.reviewed_game, review %><br>
<% end %>
<h1>Write A New Review!</h1>
<%= link_to "New Review", new_review_path %><br>
<%= link_to 'Previous Page', url_for(:back) %>

app/views/reviews/new.html.erb
 <%= flash[:alert] %>
<h1>Drop Your Review Here! </h1>

<%= form_for @review do |f| %>
    <%= f.text_area(:reviewed_game, :size => "100x20") %>
   Leave Your Rating Here: <%= f.number_field(:rating, within: 0..5) %>
    <%= f.hidden_field :purchase_id, value: @purchase_id %>
    <%= f.submit "Submit Review" %>
<% end %>
<%= link_to 'Previous Page', url_for(:back) %><br>

app/views/reviews/show.html.erb
<%= flash[:message] %>
<div class="main">
  <div class='ui raised segment'>
    <div class='ui fluid card'>
      <div class='huge content'>
        <div class='header'><h1 class="review-game"> Rating Given <%= @review.purchase_id %></h1></div>
        <div class="meta">
          <span class="date">
            <h3 id="review-given"><%= @review.reviewed_game %></h3>
          </span>
        </div>
        <div class="description">
        </div>
      </div>
    </div>
  </div>
</div>

<%= button_to 'Delete', review_path(@review), method: :delete, class: "btn btn-primary" %>
<%= button_to 'Update', edit_review_path(@review), method: :get, class: "btn btn-primary" %>
<%= link_to 'Previous Page', url_for(:back) %><br>

app/views/users/new.html.erb
<div style="margin-top: 120px;">

  <h1 id="user-form-header">Create a User</h1>
  <%= form_for :auth do |f| %>
    <div class="field">
      <%= f.text_field(:name, placeholder: 'Enter the user name...') %>
    </div>
    <div class="field">
      <%= f.text_field :password, placeholder: 'Enter the password here...' %>
    </div>
    <div class="field"> 
    </div>
    <%= f.submit "Submit" %>
  <% end %>
</div>